export const Players = [
  {
    name: "Bukayo Saka",
    team: "Arsenal",
    nationality: "England",
    rate: 86,
    img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTKp4yKD281uBgy6Tsf0LUcSKXA-K1CmAXKcH6XZU0AGB30xIgWJcsX0smiGiewnRhZ7lFLdcFx-kDPx0o",
    age: 22,
    jurseynum: 7,
  },
  {
    name: "Declan Rice",
    team: "Arsenal",
    nationality: "England",
    rate: 87,
    img: "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSe8dQT-LDsIMe4L4ytWIhpeDdmtnaMKlixi78pc5k8HQ4J9kOI-fTLqs9SJFWyl6BQPmtt8bA14wwlqeM",
    age: 24,
    jurseynum: 41,
  },
  {
    name: "Martin Ødegaard",
    team: "Arsenal",
    nationality: "Norway",
    rate: 87,
    img: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTOSidUk_oEGuXg3kYVpbexfpD4fm2p3QKqyziXgyJ1q7Wy-fa9xCRf1qWfIx_ruS__KjjCsvubx1kSzuI",
    age: 24,
    jurseynum: 8,
  },
  {
    name: "William Saliba",
    team: "Arsenal",
    nationality: "France",
    rate: 87,
    img: "https://i2-prod.mirror.co.uk/sport/football/news/article31493361.ece/ALTERNATES/n615/0_GettyImages-1789609224.jpg",
    age: 89,
    jurseynum: 2,
  },
  {
    name: "Kai Havertz",
    team: "Arsenal",
    nationality: "Germany",
    rate: 84,
    img: "https://imageio.forbes.com/specials-images/imageserve/64eb17fdff6c217d4a3b0612/Arsenal-FC-v-Fulham-FC---Premier-League/960x0.jpg?format=jpg&width=960",
    age: 24,
    jurseynum: 29,
  },
];
